### ISSUE TITLE
[FR]: Add option to Turn off Minimal theme Tables

### ISSUE THREAD

**Issue by ianTevesAcc** [kepano/obsidian-minimal-settings#87]
OB Classis Tables are better than Minimal Tables - So I'd like to use that instead
I just like the classic Obsidian tables so I'd like an option to turn off the minimal tables to be replaced with the classic OB theme tables.

Add Toggle for minimal tables for minimal theme settings
Thats it. A toggle that would turn off Minimal theme tables and be replaced with Ob classic theme tables.

Thank you ^^

**Comment by kepano** [comment]
You can already do this with Style Settings
https://minimal.guide/tables

**Comment by ianTevesAcc** [comment]
I did it thank you. Unfortunately using Style Settings wasn't able to revert everything back to classic OB tables. I did my best but was only able to achieve the following using the following css.

```css
/*Tables*/

.callout-content table thead tr th {
    font-weight: bolder;
    border-color: white;
}
table thead tr th {
    border-color: white !important;
}

/* Fix the borders and add a radius variable */
:root table {
    --table-border-radius: 5px !important;
    border-collapse: separate !important;
    border-spacing: 0 !important;
}

/* Add the radius */
th:first-child {border-top-left-radius: var(--table-border-radius)}
th:last-child {border-top-right-radius: var(--table-border-radius)}
tr:last-child td:first-child {border-bottom-left-radius: var(--table-border-radius)}
tr:last-child td:last-child {border-bottom-right-radius: var(--table-border-radius)}
  
/* Redo the borders */
:root :is(td, th) {
    border-width: 0 var(--table-border-width) var(--table-border-width) 0;
    border-color: white;
    font-size: 1.001em;
}

:root :is(td) {
    background-color: rgb(38, 37, 52) !important;
    color: rgb(232, 232, 232);
}

:root :is(th) {
    background-color: rgb(25,23,36) !important;
    color: white;
    font-weight: bolder;
}

.table-wrapper {
    overflow-x: hidden;
}
```

![image](https://github.com/kepano/obsidian-minimal-settings/assets/105651670/8b81c709-5f65-4be5-a99a-e96d351cc767)
